FPS/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('FPS/',views.dashboard,name = 'dashboard'),
    path('sell/',views.sell,name = 'sell'),
    path('requests/',views.Requests,name = 'Requests'),
    path('customers/',views.customers,name = 'customers'),
    path('ration/<int:pk>/',views.update_status,name = 'update_status'),
    path('search/',views.check_user,name = 'check_user')
]

Govt/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('Govt/',views.send,name = 'send'),
    path('Reports/',views.reports,name = 'reports'),
    path('Orders/',views.orders,name = 'orders'),
    path('People/',views.people,name = 'people'),
    path('Add/',views.add,name = 'add'),
    # path('pdf/<str:pk>',views.getpdf,name = 'pdf'),
    # path('pdf/test/',views.showPdf,name='showPdf'),
    path('report/<str:shop>/<int:month>/<int:year>',views.showPdf,name='showPdf'),
    path('searchReport/',views.searchReport,name = 'searchReport')
]

website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('FPS.urls')),
    path('',include('Govt.urls')),
    path('',include('Customer.urls')),
    path('',include('accounts.urls'))
]

Govt/models.py
from django.db import models

# Create your models here.
class RationSent(models.Model):
    shopid = models.CharField(max_length=15)
    wheat = models.IntegerField()
    rice = models.IntegerField()
    dal = models.IntegerField()
    kerosene = models.IntegerField()
    date = models.DateField(auto_now=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.shopid

class CustomerRegistration(models.Model):
    fname = models.CharField(max_length=20)
    lname = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    rationid = models.CharField(max_length=15)
    shopid = models.CharField(max_length=15)
    fire_otp = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.rationid

class ShopRegistration(models.Model):
    sname = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    shopid = models.CharField(max_length=15)
    secret_code = models.CharField(max_length=10,null=True,blank=True)

    def __str__(self):
        return self.shopid



        

Govt/forms.py
from django.forms import ModelForm
from django import forms
from .models import CustomerRegistration,ShopRegistration,RationSent
class CustomerAdd(ModelForm):
    class Meta:
        model = CustomerRegistration
        fields = '__all__'

class FPSAdd(ModelForm):
    class Meta:
        model = ShopRegistration
        fields = '__all__' 

class RationSend(ModelForm):
    class Meta:
        model = RationSent
        fields = ['shopid','wheat','dal','kerosene','rice'] 

class CustomerData(forms.Form):
    rationid = forms.CharField(max_length = 20)
    date_month = forms.IntegerField(required = False)
    date_year = forms.IntegerField(required = False)
    

Govt/views.py
from django.shortcuts import render,redirect,get_object_or_404
import requests
from accounts.decorators import govt_required
from django.contrib.auth.decorators import login_required
from .forms import CustomerAdd,FPSAdd,RationSend,CustomerData
from FPS.models import Reports,FPSRequest,SoldRation,Shop
from . models import RationSent,CustomerRegistration,ShopRegistration
from reportlab.pdfgen import canvas  
from django.http import HttpResponse,JsonResponse  
from reportlab.platypus import SimpleDocTemplate,Table,TableStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from datetime import date
from django.forms.models import model_to_dict
from django.core.paginator import Paginator
import json

# Create your views here.
months= ["January","February","March","April","May","June","July","August","September","October","November","December"]

@login_required
@govt_required
def send(request):
    context = {}
    sent = RationSent.objects.all()
    if request.method=='POST':
        form = RationSend(request.POST)
        print(context)
        if form.is_valid():
            data = form.cleaned_data
            context = {
                'dal' : data['dal'],
                'rice' : data['rice'],
                'wheat' : data['wheat'],
                'kerosene' : data['kerosene'],
                'shopid' : data['shopid'],
            }
            print(context)
            form.save()
            return redirect('send')
    form = RationSend()
    paginator = Paginator(sent, 3) # Show 3 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'Govt/send.html',{'form':form,'sent':page_obj})

@login_required
@govt_required
def reports(request):
    report = Reports.objects.all()
    paginator = Paginator(report, 3) # Show 3 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'reports': page_obj}
    return render(request,'Govt/reports.html',context)

@login_required
@govt_required
def orders(request):
    order = FPSRequest.objects.all()
    paginator = Paginator(order, 3) # Show 3 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'orders':page_obj}
    return render(request,'Govt/orders.html',context)   

@login_required
@govt_required
def people(request):
    
    today = date.today()
    generalData = {}
    dataSearch = {}
    info = {}
    if request.method=='POST':
        print('people')
        form = CustomerData(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            ration_id = data['rationid'] 
            print('is valid')
            if request.POST.get("dataSearch"):
                print('dataserach')
                try:
                    dataSearch = SoldRation.objects.get(rationid = ration_id,date_month = data['date_month'],date_year = data['date_year'])
                except SoldRation.DoesNotExist:
                    dataSearch = None

                try:
                    info = CustomerRegistration.objects.get(rationid = ration_id)
                except CustomerRegistration.DoesNotExist:
                    info = None

                try:
                    generalData = SoldRation.objects.get(rationid = ration_id,date_month = today.month,date_year = today.year)
                except SoldRation.DoesNotExist:
                    generalData = None
                
                
                

            if request.POST.get("generalData"):
                print('genraldata')
                try:
                    info = CustomerRegistration.objects.get(rationid = ration_id)
                except CustomerRegistration.DoesNotExist:
                    info = None

                try:
                    generalData = SoldRation.objects.get(rationid = ration_id,date_month = today.month,date_year = today.year)
                except SoldRation.DoesNotExist:
                    generalData = None

    else:
        form = CustomerData()   

    print('info : ')
    print(info)   
    return render(request,'Govt/people.html',{'form':form,'generalData':generalData,'info':info,'dataSearch':dataSearch})

@login_required
@govt_required
def add(request):
    context = {}
    if request.method=='POST':
        form1 = CustomerAdd(request.POST)
        form2 = FPSAdd(request.POST)
        print(context)
        if form1.is_valid():
            data = form1.cleaned_data
            context = {
                'fname' : data['fname'],
                'lname' : data['lname'],
                'address' : data['address'],
                'rationid' : data['rationid'],
                'shopid' : data['shopid'],
                'fire_otp' : data['fire_otp']
            }
            print(context)
            form1.save()
            return redirect('add')
        if form2.is_valid():
            data = form2.cleaned_data
            context = {
                'sname' : data['sname'],
                'address' : data['address'],
                'shopid' : data['shopid'],
                'secret_code' : data['secret_code']
            }
            print(context)
            form2.save()
            return redirect('add')
    
    form1 = CustomerAdd()
    form2 = FPSAdd()
    return render(request,'Govt/add.html',{'form1':form1,'form2':form2})    




# def getpdf(request,pk):  
#     text = pk
#     response = HttpResponse(content_type='application/pdf')  
#     response['Content-Disposition'] = 'inline; filename="file.pdf"'  
#     p = canvas.Canvas(response)  
#     p.setFont("Times-Roman", 55)  
#     p.drawString(100,700, text)  
#     p.showPage()  
#     p.save()  
#     return response  


 
def showPdf(request,shop,month,year):
    pdfTitle = 'Report for {} : {}'.format(months[month-1],shop)
    ration = SoldRation.objects.filter(shopid=shop,date_month=month,date_year=year)
    rations=[['Ration Id', 'Date', 'Wheat','Dal','Rice','Kerosene']]
    for item in ration:
        rations.append([item.rationid,item.date,item.wheat,item.dal,item.rice,item.kerosene])
    response = HttpResponse(content_type='application/pdf')  
    response['Content-Disposition'] = 'inline; filename="'+pdfTitle+'.pdf"' 
    filename = 'pdftable.pdf'
    data = [['RationId', 'Date', 'Wheat','Dal','Rice','Kerosene'], ['43g4hthr', '26 April', 12,34,34,34], ['43g4hthr', '26 April', 12,34,34,34], ['43g4hthr', '26 April', 12,34,34,34]]
    pdf = SimpleDocTemplate(response,rightMargin=72,leftMargin=72,topMargin=72,bottomMargin=72,title=pdfTitle) 
    table = Table(rations,80,30)
    # set style
    style = TableStyle([
        ('BACKGROUND',(0,0),(5,0),colors.black),
        ('TEXTCOLOR',(0,0),(-1,0),colors.whitesmoke),
        ('ALIGN',(0,0),(-1,-1),'CENTER'),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),
        ('FONTSIZE',(0,0),(-1,0),14),
        ('BOTTOMPADDING',(0,0),(-1,0),12)
    ])
    # add borders
    abc = TableStyle([
        ('BOX',(0,0),(-1,-1),1,colors.black),
        # ('LINBEFORE'),
        # ('LINEABOVE'),
        ('GRID',(0,1),(-1,-1),1,colors.black)
    ])
    table.setStyle(abc)
    table.setStyle(style)
    elems = []
    elems.append(table)
    pdf.build(elems)
    return response


    

def searchReport(request):
    if request.method=='POST':
        data = request.POST
        month = data.get('month')
        year = data.get('year')
        shop_id = data.get('rationid')
        print(month)
        print(year)
        try:
            shop = Shop.objects.get(shopid = shop_id )   
        except Shop.DoesNotExist:
            return JsonResponse({'found':0},status = 200)
        if month and year:
            print('not empty')
            try:
                report = Reports.objects.get(shop = shop,date_month = month,date_year = year)
            except Reports.DoesNotExist:
                report = None
            if report:
                report_data = {
                    "shopid" : shop.shopid,
                    "shopname" : getShopName(shop.shopid),
                    "date_month":report.date_month,
                    "date_year":report.date_year,


                }
               
                report_data = json.dumps(report_data)
                report_data = json.loads(report_data)
                print(report_data)
                return JsonResponse({'found':1,'report_data':report_data},status = 200)

        

    return JsonResponse({'found':0},status = 200)



def getShopName(value):
    shop = ShopRegistration.objects.get(shopid = value)
    return shop.sname 

Govt/templates/Govt/add.html
{% extends 'Govt/base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title text-center">PDS Customer Registration</h4>
        </div>
        <div class="card-body">
          <!-- form1 -->
          <!-- {{form1}} -->
          <!-- end -->
          <form method="post">
           
            {% csrf_token %}
           
            <div class="row">
             
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Name</label>
                  <input type="text" name="fname" id="id_fname" class="form-control">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Last Name</label>
                  <input type="text" name="lname" id="id_lname" class="form-control">
                </div>
              </div>
            </div>
            
           
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Address</label>
                  <input type="text" name="address" id="id_address" class="form-control">
                </div>
              </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Ration ID</label>
                    <input type="text" name="rationid" id="id_rationid" class="form-control">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Shop ID</label>
                    <input type="text" name="shopid" id="id_shopid" class="form-control">
                  </div>
                </div>
            </div>
            
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">OTP</label>
                  <input type="number" name="fire_otp" id="id_fire_otp" class="form-control">
                </div>
              </div>
          </div>
              
            <button type="submit" class="btn btn-primary pull-right">ADD </button>
            <div class="clearfix"></div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-1">
    </div>
  </div>     
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title text-center">PDS FPS Registration</h4>
        </div>
        <div class="card-body">
           <!-- form2 -->
           <!-- {{form2}} -->
           <!-- end -->
          <form method="post">
           
            {% csrf_token %}
           
            <div class="row">
             
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Shop Name</label>
                  <input type="text" name="sname" id="id_sname" class="form-control">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Address</label>
                  <input type="text" name="address" id="id_address" class="form-control">
                </div>
              </div>
            </div>
            
           
            
            <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Shop ID</label>
                    <input type="text" name="shopid" id="id_shopid" class="form-control">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">OTP</label>
                    <input type="text" name="secret_code" id="id_secret_code" class="form-control">
                  </div>
                </div>
            </div>
            
            
              
            <button type="submit" class="btn btn-primary pull-right">ADD </button>
            <div class="clearfix"></div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-1">
    </div>
  </div>     
  <script>
    $(document).ready(function() {
      $('#tab5').addClass('active');
    });
  </script>
{% endblock %}

Govt/templates/Govt/orders.html
{% extends 'Govt/base.html' %}
{% load getShopName %}
{% block content %}
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title text-center">FPS Stock Requests</h4>
          
        </div>
        <div class="card-body">
          {% if orders %}
            <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <th>
                 Shop ID
                </th>
                <th>
                 Shop Name
                </th>
                <th>
                  Date
                </th>
               
               
              </thead>
              <tbody>
                {% for order in orders %}
                  <tr>
                  <td>
                   {{ order.shop.shopid }}
                  </td>
                  <td>
                    {{ order.shop.shopid|getShopName }}
                  </td>
                  <td>
                    {{ order.date }}
                  </td>
                 
                  
                </tr>
                {% endfor %}
                
                
              </tbody>
            </table>
          </div>
          <div class="pagination pull-right">
            <span class="step-links">
                {% if orders.has_previous %}
                    <a class="btn btn-outline-primary" href="?page=1">&laquo; first</a>
                    <a class="btn btn-outline-primary " href="?page={{ orders.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ orders.number }} of {{ orders.paginator.num_pages }}
                </span>
        
                {% if orders.has_next %}
                    <a class="btn btn-outline-primary " href="?page={{ orders.next_page_number }}">next</a>
                    <a class="btn btn-outline-primary " href="?page={{ orders.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
          {% else %}
            <p>No Pending Orders</p>
          {% endif %}
          
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function() {
      $('#tab3').addClass('active');
    });
  </script>
{% endblock %}

Govt/templates/Govt/send.html
{% extends 'Govt/base.html' %}
{% block content %}
<div class="row">
    
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Ration Detail</h4>
          
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Shop ID</label>
                  <input type="text" name="shopid" id="id_shopid" class="form-control">
                </div>
              </div>
   
            </div>
            
            <h3>Quantity : </h3>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Wheat</label>
                  <input type="number" name="wheat" id="id_wheat" class="form-control">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="bmd-label-floating">Rice</label>
                  <input type="number" name="rice" id="id_rice" class="form-control">
                </div>
              </div>
              
            </div>
            <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Dal</label>
                    <input type="number" name="dal" id="id_dal" class="form-control">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Kerosene</label>
                    <input type="number" name="kerosene" id="id_kerosene" class="form-control">
                  </div>
                </div>
                
              </div>
              
            <button type="submit" class="btn btn-primary pull-right">Send </button>
            <div class="clearfix"></div>
          </form>
        </div>
      </div>
    </div>
    
  </div> 
  <div class="row">
    
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title text-center">Stocks Sent</h4>
          
        </div>
        <div class="card-body">
        {% if sent %}
         <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <th>
                 Shop ID
                </th>
                
                <th>
                  Rice 
                </th>
                <th>
                  Wheat
                </th>
                <th>
                  Dal
                </th>
                <th>
                  Kerosene
                </th>
                <th>
                  Status
                </th>
                <th>
                  Date
                </th>
                
              </thead>
              <tbody>

               {% for stock in sent %}
                <tr>
                  <td>
                    {{ stock.shopid }}
                  </td>
                  <td>
                    {{ stock.rice }}
                  </td>
                  <td>
                    {{ stock.wheat }}
                  </td>
                  <td>
                    {{ stock.dal }}
                  </td>
                  <td>
                    {{ stock.kerosene }}
                  </td>
                  <td>
                    {% if stock.status %}
                      <span class="text-success">Accepted</span>  
                    {% else %}
                    <span class="text-danger">Not Accepted</span> 
                    {% endif %}
                  </td>
                  <td>
                    {{ stock.date }}
                  </td>
                 
                </tr>
               {% endfor %}
               
                
               
              </tbody>
            </table>
          </div>
          <div class="pagination pull-right">
            <span class="step-links">
                {% if sent.has_previous %}
                    <a class="btn btn-outline-primary" href="?page=1">&laquo; first</a>
                    <a class="btn btn-outline-primary " href="?page={{ sent.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ sent.number }} of {{ sent.paginator.num_pages }}
                </span>
        
                {% if sent.has_next %}
                    <a class="btn btn-outline-primary " href="?page={{ sent.next_page_number }}">next</a>
                    <a class="btn btn-outline-primary " href="?page={{ sent.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% else %}
        <p>No stocks sent</p>
        {% endif %}
          
        </div>
      </div>
    </div>
    
  </div> 
  <script>
    $(document).ready(function() {
      $('#tab1').addClass('active');
    });
  </script>
{% endblock %}